customize_image: move ld.so.preload while in chroot
Since Buster the ld.so.preload contains the following line:
/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so
This results in the following error message:
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so'
from /etc/ld.so.preload cannot be preloaded (cannot open shared object
file): ignored.

As we don't need this library during installation we move it to avoid
the error messages.

Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>